feat: add support for realtime group info refresh
ethereum-push-notification-service/push-restapi-dart pull request #51
Opened 2023-10-04 09:06 UTC by gbogboadePush

2023-10-04 09:46 UTC, madhur-push requested changes
Realtime messages aren't showing up on the UI, I can see them in the sockets log though.

2023-10-06 11:39 UTC, madhur-push requested changes
The requests aren't reflecting in realtime.

2023-10-06 11:39 UTC, madhur-push commented on example/lib/views/account_provider.dart
> +        ref.read(requestsProvider).loadRequests();
@Gbogboade1 We are getting the request here itself, we dont have to call loadRequests() imo, we just need to put that requests in the list of requests.

2023-10-06 11:46 UTC, Gbogboade1 commented on example/lib/views/account_provider.dart
> +        ref.read(requestsProvider).loadRequests();
The api call is done to ensure the list is loaded with the most accurate data...other items in the list  may no longer exist

2023-10-06 11:54 UTC, madhur-push commented on example/lib/views/account_provider.dart
> +        ref.read(requestsProvider).loadRequests();
Ayo, lets say you receive a request, the only way in which this request will come out of the requests list is when you will accept it correct? What im trying to say is the only way in which a request will get removed from the requests list is when a user will accept it, and the way in which a request will get added is via the sockets. We cant call the requests API after every socket event reason being what if there are many many requests right, in that case we'll unnecessarily exhaust the BE.

One thing we need to check is lets say I have a request and my request gets cancelled then in that case, is a socket event getting received or no. Lets make a ticket for the last thing I mentioned.

2023-10-23 07:43 UTC, madhur-push approved these changes
LGTM

2023-10-23 07:43 UTC, merged