Example app UI updates
ethereum-push-notification-service/push-restapi-dart pull request #60
Opened 2023-11-06 18:37 UTC by gbogboadePush

https://www.notion.so/pushprotocol/Add-spaces-feeds-spaces-invites-component-in-the-example-app-and-add-socket-support-63d25a7acd1e4001be4a4e8dff94304c?pvs=4

2023-11-09 04:23 UTC, madhur-push requested changes

2023-11-09 06:39 UTC, gbogboadePush commented on example/lib/views/spaces/trending_space_screen.dart
> -import 'package:flutter_riverpod/flutter_riverpod.dart';
yeah, I will delete the file 
we need to include a search feature to the spaces later

2023-11-10 03:07 UTC, madhur-push requested changes
When I create a space and go to invites section of the participants end, an error is thrown.

2023-11-13 06:45 UTC, madhur-push approved these changes
LGTM, good work @Gbogboade1! :)

2023-11-13 06:47 UTC, merged